# Generated by Django 5.2.11 on 2026-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_item_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='synopsis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
