# Generated by Django 5.2.11 on 2026-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_item_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comic',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='season',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tv',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
