# Generated by Django 5.2.11 on 2026-02-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_media_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_media_type_valid',
        ),
        migrations.AddField(
            model_name='anime',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comic',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tv',
            name='caught_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame')], default='movie', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['anime', 'manga', 'tv', 'season', 'episode', 'movie', 'game', 'book', 'comic', 'boardgame'])), name='app_item_media_type_valid'),
        ),
    ]
