# Generated by Django 5.2.11 on 2026-02-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_add_caught_up_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicmedia',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comic',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tv',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
    ]
