# Generated by Django 5.2.11 on 2026-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_add_is_rewatch_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='english_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
