# Generated by Django 5.2.11 on 2026-03-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_add_english_title_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game')], default='movie', max_length=10),
        ),
    ]
