# Generated by Django 5.2.11 on 2026-03-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_add_pin_order_to_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('sequel', 'Sequel'), ('prequel', 'Prequel')], max_length=20)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='app.item')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='app.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_item', 'to_item', 'relation_type'), name='unique_item_relationship')],
            },
        ),
    ]
