# Generated by Django 5.2.11 on 2026-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_itemrelationship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('item', 'related_season', 'end_date'), name='app_episode_unique_play'),
        ),
    ]
