services:
  docket:
    container_name: docket
    image: ghcr.io/osaidahmed/docket
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - TZ=Europe/Berlin
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=docket
      - DB_USER=docket
      - DB_PASSWORD=docket
      - DB_PORT=5432
    ports:
      - "8000:8000"

  db:
    image: postgres:18-alpine
    container_name: docket-db
    environment:
      - POSTGRES_DB=docket
      - POSTGRES_USER=docket
      - POSTGRES_PASSWORD=docket
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: docket-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
