# Generated by Django 5.2.11 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_add_english_title_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0049_add_hide_zero_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='last_search_type_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='media_type_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame')], default='tv', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['anime', 'manga', 'tv', 'movie', 'game', 'book', 'comic', 'boardgame'])), name='last_search_type_valid'),
        ),
    ]
