# Generated by Django 5.2.11 on 2026-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_user_last_search_type_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_scheme',
            field=models.CharField(choices=[('charcoal', 'Charcoal'), ('ocean', 'Ocean'), ('twilight', 'Twilight'), ('forest', 'Forest'), ('ember', 'Ember'), ('sakura', 'Sakura')], default='charcoal', max_length=20),
        ),
    ]
