# Generated by Django 5.2.11 on 2026-02-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_user_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_default_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
