# Generated by Django 5.2.11 on 2026-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_add_english_title_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0052_user_home_default_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_truncation',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('10', '10'), ('0', 'All')], default='0', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_truncation__in', ['3', '5', '10', '0'])), name='home_truncation_valid'),
        ),
    ]
