# Generated by Django 5.2.11 on 2026-02-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_add_english_title_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0053_user_home_truncation_user_home_truncation_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_group',
            field=models.CharField(choices=[('type', 'Type'), ('status', 'Status')], default='type', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='home_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='cards', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_layout__in', ['cards', 'grid', 'table'])), name='home_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_group__in', ['type', 'status'])), name='home_group_valid'),
        ),
    ]
