# Generated by Django 5.2.11 on 2026-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_user_home_layout_home_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='export_txt_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
