# Generated by Django 5.2.11 on 2026-03-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0055_user_export_txt_config'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tv_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='season_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='anime_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='manga_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_layout_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='book_layout_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='boardgame_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='boardgame_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game')], default='tv', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_layout__in', ['cards', 'grid', 'table'])), name='tv_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_layout__in', ['cards', 'grid', 'table'])), name='season_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_layout__in', ['cards', 'grid', 'table'])), name='movie_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_layout__in', ['cards', 'grid', 'table'])), name='anime_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_layout__in', ['cards', 'grid', 'table'])), name='manga_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_layout__in', ['cards', 'grid', 'table'])), name='game_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_layout__in', ['cards', 'grid', 'table'])), name='book_layout_valid'),
        ),
    ]
