# Generated by Django 5.2.11 on 2026-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_add_status_sort_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_related_media',
            field=models.BooleanField(default=False, help_text='Group related seasons and sequels on list pages'),
        ),
    ]
