# Generated by Django 5.2.11 on 2026-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_itemrelationship'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0058_user_group_related_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive_sort',
            field=models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='end_date', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('archive_sort__in', ['score', 'title', 'start_date', 'end_date'])), name='archive_sort_valid'),
        ),
    ]
