# Generated by Django 5.2.11 on 2026-03-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_add_archive_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('layout', models.CharField(choices=[('cards', 'Cards'), ('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20)),
                ('sort', models.CharField(choices=[('score', 'Score'), ('title', 'Title'), ('progress', 'Progress'), ('status', 'Status'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20)),
                ('status_filter', models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'media_type'), name='unique_user_media_pref')],
            },
        ),
    ]
