# Generated by Django 5.2.11 on 2026-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_remove_per_type_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
